import type { Task } from '@/BLL/taskManager/types'

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Implement password reset flow',
    description:
      'Build the end-to-end password reset experience with token validation, email delivery, and expired-link handling.',
    priority: 'high',
    dueDate: '2026-06-18',
    assignees: ['Maya Chen', 'Noah Williams'],
    status: 'todo',
    displayStatus: 'not-started',
    tags: ['auth', 'frontend', 'security'],
    createdAt: '2026-06-01T09:15:00.000Z',
  },
  {
    id: 'task-002',
    title: 'Add dashboard loading skeletons',
    description:
      'Replace blank dashboard states with skeleton loaders that match the final card and table layout.',
    priority: 'medium',
    dueDate: '2026-07-08',
    assignees: ['Ethan Brooks'],
    status: 'todo',
    displayStatus: 'not-started',
    tags: ['ux', 'frontend'],
    createdAt: '2026-06-03T11:30:00.000Z',
  },
  {
    id: 'task-003',
    title: 'Define billing event audit trail',
    description:
      'Document the event schema for subscription changes, failed payments, refunds, and invoice retries.',
    priority: 'low',
    dueDate: '2026-07-16',
    assignees: ['Priya Raman'],
    status: 'todo',
    displayStatus: 'not-started',
    tags: ['billing', 'docs'],
    createdAt: '2026-06-05T14:10:00.000Z',
  },
  {
    id: 'task-004',
    title: 'Resolve invite acceptance bug',
    description:
      'Fix the team invite flow where accepted invitations sometimes leave users on the pending members list.',
    priority: 'high',
    dueDate: '2026-06-24',
    assignees: ['Lucas Martin', 'Priya Raman'],
    status: 'todo',
    displayStatus: 'not-started',
    tags: ['backend', 'blocked', 'teams'],
    createdAt: '2026-06-07T10:45:00.000Z',
  },
  {
    id: 'task-005',
    title: 'Optimize task search endpoint',
    description:
      'Improve query performance for task search by reviewing indexes, pagination, and response payload size.',
    priority: 'high',
    dueDate: '2026-06-28',
    assignees: ['Noah Williams', 'Ethan Brooks'],
    status: 'in-progress',
    displayStatus: 'on-track',
    tags: ['backend', 'performance'],
    createdAt: '2026-06-08T08:40:00.000Z',
  },
  {
    id: 'task-006',
    title: 'Refine onboarding checklist copy',
    description:
      'Update onboarding checklist labels and empty states so new workspace owners understand their next actions.',
    priority: 'medium',
    dueDate: '2026-07-05',
    assignees: ['Maya Chen'],
    status: 'in-progress',
    displayStatus: 'in-research',
    tags: ['ux', 'copy'],
    createdAt: '2026-06-10T13:25:00.000Z',
  },
  {
    id: 'task-007',
    title: 'Add webhook retry visibility',
    description:
      'Expose retry attempts and last failure messages for outgoing webhooks in the workspace integrations page.',
    priority: 'medium',
    dueDate: '2026-07-12',
    assignees: ['Priya Raman', 'Lucas Martin'],
    status: 'in-progress',
    displayStatus: 'on-track',
    tags: ['integrations', 'backend'],
    createdAt: '2026-06-12T15:00:00.000Z',
  },
  {
    id: 'task-008',
    title: 'Review mobile navigation spacing',
    description:
      'Audit the compact navigation treatment for tablet widths and document the remaining responsive gaps.',
    priority: 'low',
    dueDate: '2026-07-20',
    assignees: ['Ethan Brooks'],
    status: 'in-progress',
    displayStatus: 'in-research',
    tags: ['ux', 'responsive'],
    createdAt: '2026-06-14T09:50:00.000Z',
  },
  {
    id: 'task-009',
    title: 'Ship saved filter presets',
    description:
      'Persist user-defined task filters and make them available from the task list toolbar.',
    priority: 'medium',
    dueDate: '2026-06-26',
    assignees: ['Lucas Martin'],
    status: 'done',
    displayStatus: 'completed',
    tags: ['frontend', 'filters'],
    createdAt: '2026-06-02T12:15:00.000Z',
  },
  {
    id: 'task-010',
    title: 'Complete API token rotation',
    description:
      'Allow workspace admins to rotate API tokens and immediately revoke the previous token.',
    priority: 'high',
    dueDate: '2026-06-20',
    assignees: ['Noah Williams'],
    status: 'done',
    displayStatus: 'completed',
    tags: ['security', 'backend'],
    createdAt: '2026-05-28T16:35:00.000Z',
  },
  {
    id: 'task-011',
    title: 'Update notification preferences UI',
    description:
      'Group notification channels by product area and clarify which alerts are sent immediately.',
    priority: 'low',
    dueDate: '2026-07-01',
    assignees: ['Maya Chen'],
    status: 'done',
    displayStatus: 'completed',
    tags: ['frontend', 'notifications'],
    createdAt: '2026-06-04T10:05:00.000Z',
  },
  {
    id: 'task-012',
    title: 'Validate export CSV formatting',
    description:
      'Confirm exported task reports preserve dates, priority labels, assignees, and tag columns across spreadsheet tools.',
    priority: 'low',
    dueDate: '2026-07-24',
    assignees: [],
    status: 'done',
    displayStatus: 'completed',
    tags: [],
    createdAt: '2026-06-11T11:20:00.000Z',
  },
]
